// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial3pjxx.CodeFirst;

#nullable disable

namespace Parcial3pjxx.Migrations
{
    [DbContext(typeof(FacturadorDbContext))]
    partial class FacturadorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial3pjxx.Cliente", b =>
            {
                b.Property<int>("IdCliente")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                b.Property<string>("CuilCuit")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Domicilio")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RazonSocial")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("IdCliente");

                b.ToTable("Clientes");
            });

            modelBuilder.Entity("Parcial3pjxx.Factura", b =>
            {
                b.Property<int>("IdFactura")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                b.Property<int>("ClienteIdCliente")
                    .HasColumnType("int");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime2");

                b.Property<int>("IdCliente")
                    .HasColumnType("int");

                b.Property<float>("ImporteTotal")
                    .HasColumnType("real");

                b.Property<int>("Numero")
                    .HasColumnType("int");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("IdFactura");

                b.HasIndex("ClienteIdCliente");

                b.ToTable("Facturas");
            });

            modelBuilder.Entity("Parcial3pjxx.Item", b =>
            {
                b.Property<int>("IdItem")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                b.Property<int>("Cantidad")
                    .HasColumnType("int");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("FacturaIdFactura")
                    .HasColumnType("int");

                b.Property<int>("IdFactura")
                    .HasColumnType("int");

                b.Property<float>("Importe")
                    .HasColumnType("real");

                b.HasKey("IdItem");

                b.HasIndex("FacturaIdFactura");

                b.ToTable("Items");
            });

            modelBuilder.Entity("Parcial3pjxx.Factura", b =>
            {
                b.HasOne("Parcial3pjxx.Cliente", "Cliente")
                    .WithMany("Facturas")
                    .HasForeignKey("ClienteIdCliente")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Cliente");
            });

            modelBuilder.Entity("Parcial3pjxx.Item", b =>
            {
                b.HasOne("Parcial3pjxx.Factura", "Factura")
                    .WithMany("Items")
                    .HasForeignKey("FacturaIdFactura")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Factura");
            });

            modelBuilder.Entity("Parcial3pjxx.Cliente", b =>
            {
                b.Navigation("Facturas");
            });

            modelBuilder.Entity("Parcial3pjxx.Factura", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}